facebook:
  client:
    clientId: 1830494810499656
    clientSecret: 94fb1f3e1d1bb78c0718ae7d72a4eff8
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG